### ISSUE TITLE
Update update-trinity

### ISSUE THREAD

**Issue by Grazfather** [hugsy/stuff#1]
If `python` points to `python3`, then building will fail.

Fixed version is here:

https://gist.githubusercontent.com/Grazfather/91e1ea3c3b51be844552263ce0f0d538/raw/c5607a51047b4dc01bf1f3fd443e8cd6318056c6/install-trinity.sh

**Comment by Grazfather** [comment]
Could also be sped up by using `git clone --depth 1`
Also it calls `ldconfig` to update the library search paths, and issue I had in some docker images.

**Comment by hugsy** [comment]
453fdcb01afe8ddeab855e0a6a6cfe86cf63391b
